version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: yarn
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Build project
          command: yarn build
      - run:
          name: Lint
          command: yarn lint
      - run:
          name: Test
          command: yarn test
      - sonarcloud/scan

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.0

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud
